# Generated by Django 3.0.5 on 2020-09-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0002_bio_writeup'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='photo',
            field=models.FileField(default='photo', upload_to=''),
            preserve_default=False,
        ),
    ]
