# Generated by Django 3.0.5 on 2020-10-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0005_auto_20200930_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='draft',
            field=models.BooleanField(default=False, help_text='Do you want to save this writeup as draft?'),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
