# Generated by Django 3.0.5 on 2020-10-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0007_auto_20201005_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='photo',
        ),
        migrations.AddField(
            model_name='bio',
            name='genre',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='quote',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='school',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
