# Generated by Django 3.0.5 on 2020-10-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0008_auto_20201006_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='mobile_no',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
