# Generated by Django 3.0.5 on 2020-10-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0013_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.AddField(
            model_name='follow',
            name='follow',
            field=models.CharField(default='admin', max_length=250),
            preserve_default=False,
        ),
    ]
