# Generated by Django 3.0.5 on 2020-10-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0014_auto_20201007_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writeup',
            name='favourites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writeup',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
