# Generated by Django 3.0.5 on 2020-10-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0015_auto_20201008_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
