# Generated by Django 3.0.5 on 2020-10-17 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0018_writeup_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
